config/routes.rb
Rails.application.routes.draw do


  namespace :admins do
    root to: 'homes#top'
    devise_for :users, controllers: {
      sessions: 'admins/users/sessions',
      registrations: 'admins/users/registrations',
      passwords: 'admins/users/passwords'
    }
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  scope module: :customers do
    root to: 'homes#top'
    devise_for :end_users, controllers: {
      sessions: 'customers/end_users/sessions',
      registrations: 'customers/end_users/registrations',
      passwords: 'customers/end_users/passwords'
    }
    resources :end_users
    get 'end_users/:id/confirm' => 'end_users#confirm', as: :end_user_confirm
    patch 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: :withdrawal
    resources :items, only: [:index, :show]
    delete 'cart_items/empty' => 'cart_items#empty', as: :empty
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/thanks' => 'orders#thanks', as: :thanks
    post 'orders/confirm' => 'orders#confirm', as: :order_confirm
    resources :orders, only: [:index, :new, :create, :show]
    get 'homes/about' => 'homes#about', as: :about
    get 'genres/:id' => 'genres#search', as: :search
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user
	has_many :order_details, dependent: :destroy

	validates :direction, presence: true
	validates :address, presence: true
	validates :postcode, presence: true

	enum payment_type: {
		クレジットカード: 0,
		銀行振り込み: 1
	}

	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admins_user!
  def index
    @orders = Order.all

  end

  def show
  	@orders = Order.all
  	@order = Order.find(params[:id])


  end

  def update
  	@order = Order.find(params[:id])
    @order.order_status = params[:order][:order_status].to_i
    # @order.update(order_params)
    # redirect_to admins_orders_path
    @order.update(order_params)
    if @order.order_status == "入金確認" #注文ステータスが入金確認の場合
        @order.order_details.each do |order_detail| #全ての製作ステータスを更新する
          order_detail.item_status = 1
          order_detail.save
        end
    end
    redirect_to admins_orders_path
  end

  private
    def order_params
      params.require(:order).permit(:order_status)
    end

    def order_detail_params
      params.require(:order).permit(:item_status)
    end

end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
before_action :authenticate_end_user!
	def index
       @cart_items = CartItem.where(end_user_id: current_end_user.id)
       # cart_item = CartItem.find(params[:id])
       # @items = @cart_item.item
       # @price_with_tax = @cart_item.item.non_tax_price.to_i * 1.1
       # @subtotal = @price_with_tax * quantity
	end

	def create
		cart_item =CartItem.new(cart_items_params)
		cart_item.end_user_id = current_end_user.id
		if current_end_user.cart_items.where(item_id: cart_item.item_id).exists?#cart_item.item_idパラメータで渡しているcart_itemに紐づくitem_id
			 redirect_back(fallback_location: root_path, notice: "カートに商品はあります。")
		else
			 cart_item.save
		   redirect_to cart_items_path, notice: "カートに商品を入れました。"
		end
	end
#destroyメソッドはwhereと併せて使うらしい
	def empty
		cart_item = CartItem.where(params[:id])
		cart_item.destroy_all
		redirect_back(fallback_location: root_path, notice: "successfully delete")
	end

	def destroy
		cart_item = CartItem.find(params[:id])
        cart_item.destroy
        redirect_back(fallback_location: root_path, notice: "successfully delete")
	end

	def update
		cart_item = CartItem.find(params[:id])
		# cart_item.update
		cart_item.update(cart_items_params)
		redirect_back(fallback_location: root_path)
	end

	private
	def cart_items_params
		params.require(:cart_item).permit(:item_id, :quantity)
	end

end

app/controllers/customers/deliveries_controller.rb
class Customers::DeliveriesController < ApplicationController
	before_action :authenticate_end_user!
	before_action :baria_delivery, only: [:edit, :update]#他の人が更新できないように
	def create
		@delivery = Delivery.new(delivery_params)
		@delivery.end_user_id = current_end_user.id
		if @delivery.save
			flash[:notice] = "配送先が登録されました"
		   redirect_back(fallback_location: deliveries_path)
		else
		   @deliveries = Delivery.where(end_user_id: current_end_user)
		   render :index
		end
	end

	def index
		@deliveries = Delivery.where(end_user_id: current_end_user)#current_end_userに紐づく登録住所
		@delivery = Delivery.new
	end

	def edit
		@delivery = Delivery.find(params[:id])
	end

	def update
		@delivery = Delivery.find(params[:id])
		if @delivery.update(delivery_params)
		   redirect_to deliveries_path, notice: "配送先情報が更新されました"
		else
			render :edit
		end
	end

	def destroy
		@delivery = Delivery.find(params[:id])
		@delivery.destroy
		redirect_to deliveries_path
	end

	private
	def delivery_params
		params.require(:delivery).permit(:postcode, :direction, :address)
	end

   def baria_delivery
    @delivery = Delivery.find(params[:id])
    if @delivery.end_user_id != current_end_user.id
       redirect_to deliveries_path
    end
	end
end

app/controllers/customers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/end_users/passwords_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/end_users/registrations_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/end_users/sessions_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @end_user = EndUser.find_by(email: params[:end_user][:email].downcase)
    if @end_user
      if (@end_user.valid_password?(params[:end_user][:password]) && (@end_user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_end_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class Customers::EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/end_users_controller.rb
class Customers::EndUsersController < ApplicationController
  before_action :authenticate_end_user!
  def index
  end

  def show
  	@end_user = current_end_user
  end

  def edit
  	@end_user = current_end_user
  end

  def update
  	@end_user = current_end_user
  	if @end_user.update(end_user_params)
  	   redirect_to end_user_path(@end_user), notice: "会員情報が更新されました。"
    else
      render :edit
    end
  end

  def confirm
    @end_user = current_end_user
  end
  # 退会するためのアクション
  def withdrawal
    end_user = current_end_user
      end_user.is_deleted == false
      end_user.update(is_deleted: true)
      redirect_to root_path
      #sessionはユーザーの情報を持っているので、強制的にresetで消している。
      reset_session
  end

  private
  def end_user_params
  	params.require(:end_user).permit(:is_delete, :first_name, :last_name, :first_kana_name, :last_kana_name, :postcode, :address, :phone_number, :email)
  end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  def search
  	#ジャンルに紐づく商品の探し方。whereメソッドでアイテムテーブルの中にあるジャンルＩＤを取り出す。
  	@items = Item.where(genre_id: params[:id])

  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
	def top
	  @genre = Genre.all
	  @items = Item.all.shuffle.first(4)
	end

	def about
	end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

	def index
		@items = Item.all
		# @item = Item.find(params[:id])
		@items = Item.page(params[:page])
	end

	def show
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_end_user!
  def index #注文履歴一覧
  	@orders = Order.where(end_user_id: current_end_user.id) #ログイン中のユーザーの注文履歴を表示
  end

  def new #注文登録画面
  	@order = Order.new
  end

  def confirm #注文確認画面。分岐ごとに代入する値を定義
    if order_params[:select_address] == "1" #お届け先でご自身の住所を選んだ場合
      @address = current_end_user.address
      @postcode = current_end_user.postcode
      @direction = current_end_user.first_name+current_end_user.last_name
      @a = 0
    elsif order_params[:select_address] == "2" #お問合せで登録済み住所から選択を選んだ場合
      delivery = Delivery.find(order_params[:address_id])
      @address = delivery.address
      @postcode = delivery.postcode
      @direction = delivery.direction
      @a = 0
    else #お届け先で新しいお届け先を選んだ場合
      @address = order_params[:address]
      @postcode = order_params[:postcode]
      @direction = order_params[:direction]
      @a = 1
    end
    @cart_item = CartItem.where(end_user_id: current_end_user.id)
    @cart_items = current_end_user.cart_items
    @payment_type = order_params[:payment_type]
    @total_price = 0
    current_end_user.cart_items.each do |cart_item|
      @total_price += cart_item.item.non_taxed_price * cart_item.quantity #請求金額 追加4/23 計算を合わせるため修正
    end
    @order = Order.new
    @order.postage = 800
  end

  def create
    order = Order.new(order_params)
    order.end_user_id = current_end_user.id
    order.order_status = 0 #order_statusをデフォルトで0に設定
    order.postage = 800 #送料を800円に設定
    order.tax = 1.1 #消費税を10%に設定
    if a_params[:a] == "1" #新しいお届け先を選択していた場合、配送先を保存する
      # delivery = Delivery.new(order_deli_params)
      # delivery.end_user_id = current_end_user.id
      delivery = current_end_user.deliveries.new(order_deli_params)
      delivery.save
    end
    if order.save #注文確定
      current_end_user.cart_items.each do |cart_item| #注文詳細履歴作成。1カートごとに注文詳細履歴を作る。
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item.id
        order_detail.price = cart_item.item.non_taxed_price
        order_detail.quantity = cart_item.quantity
        order_detail.item_status = 0
        order_detail.order_id = order.id
        order_detail.save #注文履歴保存
      end
      current_end_user.cart_items.destroy_all #カートを空にする
      redirect_to thanks_path
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
    # @order.order_details = OrderDetail.where(order_id: @order.id)
  end

  private
  def order_params
    params.require(:order).permit(:total_price, :postcode, :address, :direction, :payment_type, :select_address, :address_id)
  end

  def a_params
     params.require(:order).permit(:a)
  end

  def order_deli_params
    params.require(:order).permit(:address, :postcode, :direction)
  end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/deliveries_helper.rb
module Customers::DeliveriesHelper
end

app/helpers/customers/end_users_helper.rb
module Customers::EndUsersHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/views/customers/orders/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3 col-xs-offset-1">
			<div class="sign-title">
				<h2>注文情報確認</h2>
			</div>
		</div>
	</div>

	<div class="row">

		<div class="col-xs-6 col-xs-offset-1">
			<table class="table">


				<thead>
					<tr>
						<th>商品名</th>
						<th>単価（税込み）</th>
						<th>数量</th>
						<th>小計</th>
					</tr>
				</thead>

				<tbody>
					<% @sum = 0 %>
					<% @cart_items.each do |cart_item| %>

						<tr>
							<td><%= attachment_image_tag(cart_item.item, :image, size: "50x50") %>
								  <%= cart_item.item.name %>
							</td>
							<td><%= (cart_item.item.non_taxed_price*1.1).floor.to_s(:delimited) %></td>
							<td><%= cart_item.quantity %></td>
							<td><%= (cart_item.item.non_taxed_price*cart_item.quantity*1.1).floor.to_s(:delimited) %></td>
						</tr>
						<% @sum += cart_item.item.non_taxed_price*cart_item.quantity*1.1%>
					<% end %>
				</tbody>

			</table>
		</div>

		<div class="col-xs-3 col-xs-offset-1">


			<table class="table">
				<tbody>
					<tr>
						<th>商品合計</th>
						<td><%= @sum.floor.to_s(:delimited) %></td>
					</tr>
					<tr>
						<th>送料</th>
						<td><%= @order.postage %></td>
					</tr>
					<tr>
						<th>請求金額</th>
						<td> <%= (@sum + @order.postage).floor.to_s(:delimited) %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

		<%= form_with model: @order, url: orders_path, local: true do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<%= f.label :お支払い方法 %>
		</div>
		<div class="col-xs-2">
			<%= @payment_type %>
			<%= f.hidden_field :payment_type, :value => @payment_type %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<%= f.label :お届け先 %>
		</div>
		<div class="col-xs-6">
			〒 <%= @postcode %><%= @address %>
			<%= f.hidden_field :postcode, :value => @postcode %>
			<%= f.hidden_field :address, :value => @address %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<%= f.label :宛先 %>
		</div>
		<div class="col-xs-6">
			<%= @direction %>
			<%= f.hidden_field :direction, :value => @direction %>
			<%= f.hidden_field :a, :value => @a %>
		</div>
	</div>

<!-- 表示を整えたかったため一旦コメントアウトしました。 -->
			<%#= f.label :請求金額 %>
			<%= f.hidden_field :total_price, :value => @total_price %>
			<%#= @total_price %>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-5">
			<%= f.submit '購入を確定する', class: "btn btn-primary btn-block" %>
		<% end %>
	</div>

app/views/customers/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
      <div class="sign-title">

				<h1>注文履歴一覧</h1>

			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-8 col-xs-offset-1">
			<table class="table">

				<thead>
					<tr>
						<th>注文日</th>
						<th>配送先</th>
						<th>注文商品</th>
						<th>支払金額</th>
						<th>ステータス</th>
						<th>注文詳細</th>
						<th colspan="6"></th>
					</tr>
				</thead>

				<tbody>
					<% @orders.each do |order| %>
						<tr>
							<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
							<td>〒 <%= order.postcode %><br>
								<%= order.address %><br>
								<%= order.direction %>
							</td>
							<td>
								<% order.order_details.each do |order_detail| %>
									<%= order_detail.item.name %><br>
								<% end %>
							 </td><!--送料も*tax1.1されていたので入れ替えました -->
							<td><%= ((order.total_price * order.tax) + order.postage ).floor.to_s(:delimited) %> 円</td>
							<td><%= order.order_status %></td>
							<td><%= link_to "表示する", order_path(order) %></td>
						</tr>
					<% end %>
				</tbody>

			</table>
		</div>
	</div>
</div>

app/views/customers/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
      <div class="title">
      	<h2>注文情報入力</h2>
      </div>
    </div>
  </div>

  <%= form_with model: @order, url: order_confirm_path, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
			<h4>お支払い方法</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
			<%= f.radio_button :payment_type, :クレジットカード, :checked => true %>
      <%= f.label :クレジットカード %><br>

			<%= f.radio_button :payment_type, :銀行振り込み %>
      <%= f.label :銀行振り込み %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
			<h4>お届け先</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-5 col-xs-offset-1">

			<%= f.radio_button :select_address, 1, :checked => true %>
      <%= f.label :ご自身の住所 %><br>

			<%= f.radio_button :select_address, 2 %>
      <%= f.label :登録済み住所から選択 %><br>
			<%= f.collection_select(:address_id, current_end_user.deliveries, :id, :address ) %><br>

			<%= f.radio_button :select_address, 3 %>
      <%= f.label :新しいお届け先 %><br>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-1">
			<%= f.label :郵便番号ハイフンなし %>
    </div>
    <div class="col-xs-8 col-xs-offset-1">
      <div class="sign-field">
			<%= f.text_field :postcode %>
    </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-1">
			<%= f.label :住所 %>
    </div>
    <div class="col-xs-8 col-xs-offset-1">
      <div class="sign-field">
			<%= f.text_field :address %>
    </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-1">
			<%= f.label :宛名 %>
    </div>
    <div class="col-xs-8 col-xs-offset-1">
      <div class="sign-field">
			<%= f.text_field :direction %>
    </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-3">
			<%= f.submit '確認画面へ進む', class: "btn btn-primary btn-block" %>
    </div>
  </div>

  <% end %>
</div>

app/views/customers/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-1">
      <div class="sign-title">

				<h2>注文履歴詳細</h2>
			</div>
		</div>
	</div>
 	<div class="row">
		<div class="col-xs-6 col-xs-offset-1">
			<h4>注文情報</h4>
			<table class="table">
				<thead>
					<tr>
						<th colspan="2"></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>注文日</td>
						<td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
					</tr>
					<tr>
						<td>配送先</td>
						<td>〒 <%= @order.postcode %>
								<%= @order.address %><br>
								<%= @order.direction %>
						</td>
					</tr>
					<tr>
						<td>支払い方法</td>
						<td><%= @order.payment_type %></td>
					</tr>
					<tr>
						<td>ステータス</td>
						<td><%= @order.order_status %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="col-xs-3 col-xs-offset-1">
			<h4>請求情報</h4>
			<table class="table">
					<tr>
						<td>商品合計</td> <!--taxの追加 -->
						<td><%= (@order.total_price * @order.tax).floor.to_s(:delimited) %></td>
					</tr>
					<tr>
						<td>配送料</td>
						<td><%= @order.postage %></td>
					</tr>
					<tr>
						<td><strong>ご請求額</strong></td><!--送料も*tax1.1されていたので入れ替えました -->
						<td><%= ((@order.total_price * @order.tax) + @order.postage ).floor.to_s(:delimited) %></td>
					</tr>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-6 col-xs-offset-1">
			<h4>注文内容</h4>
			<table class="table">
				<thead>
					<tr>
						<th>商品</th>
						<th>単価（税込）</th>
						<th>個数</th>
						<th>小計</th>
						<th colspan="4"></th>
					</tr>
				</thead>
				<tbody>
					<% @order.order_details.each do |order_detail| %>
						<tr>
							<td><%= order_detail.item.name %></td>
							<td><%= (order_detail.price * @order.tax).floor.to_s(:delimited) %></td>
							<td><%= order_detail.quantity %></td>
							<td><%= (order_detail.quantity * order_detail.price * @order.tax).floor.to_s(:delimited) %></td><!--taxの追加 -->
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/customers/orders/thanks.html.erb
<div class="confirm-text">
		<h3><label>ご購入ありがとうございました！</label></h3>
</div>