config/routes.rb
Rails.application.routes.draw do


  namespace :admins do
    root to: 'homes#top'
    devise_for :users, controllers: {
      sessions: 'admins/users/sessions',
      registrations: 'admins/users/registrations',
      passwords: 'admins/users/passwords'
    }
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  scope module: :customers do
    root to: 'homes#top'
    devise_for :end_users, controllers: {
      sessions: 'customers/end_users/sessions',
      registrations: 'customers/end_users/registrations',
      passwords: 'customers/end_users/passwords'
    }
    resources :end_users
    get 'end_users/:id/confirm' => 'end_users#confirm', as: :end_user_confirm
    patch 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: :withdrawal
    resources :items, only: [:index, :show]
    delete 'cart_items/empty' => 'cart_items#empty', as: :empty
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/thanks' => 'orders#thanks', as: :thanks
    post 'orders/confirm' => 'orders#confirm', as: :order_confirm
    resources :orders, only: [:index, :new, :create, :show]
    get 'homes/about' => 'homes#about', as: :about
    get 'genres/:id' => 'genres#search', as: :search
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :end_user
	belongs_to :item

	validates :quantity, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :end_user

	validates :direction, presence: true
	validates :address, presence: true
	validates :postcode, presence: true

	def full_address
		self.postcode + self.address + self.direction
	end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_kana_name, presence: true, format: { with: /\A[ぁ-んァ-ヶー－]+\z/ } #全角カタカナ
  validates :last_kana_name, presence: true, format: { with: /\A[ぁ-んァ-ヶー－]+\z/ }
  validates :postcode, presence: true, format: { with: /\A[0-9]+\z/ } #半角数字
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && (self.is_deleted == "有効")
  end

  enum is_deleted: {
    退会済: true,
    有効: false
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy

	validates :name, presence: true

	enum is_valid: {
		売切れ: true,
		販売中: false
	}
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :image
	has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	belongs_to :genre

	validates :name, presence: true
	validates :detail, presence: true
	validates :non_taxed_price, presence: true
	validates :image, presence: true

	enum is_valid: {
		無効: true,
		有効: false
	}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user
	has_many :order_details, dependent: :destroy

	validates :direction, presence: true
	validates :address, presence: true
	validates :postcode, presence: true

	enum payment_type: {
		クレジットカード: 0,
		銀行振り込み: 1
	}

	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item

	enum item_status: {
		着手不可: 0,
		製作待ち: 1,
		製作中: 2,
		製作完了:3
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admins_user!
  def index
  	@genre = Genre.new
  	@genres = Genre.all
  end

  def create
  	@genre = Genre.new(genre_params)
  	if @genre.save
  	   redirect_to admins_genres_path, notice: "ジャンルが登録されました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  	@genre = Genre.find(params[:id])
  end

  def update
  	@genre = Genre.find(params[:id])
  	if @genre.update(genre_params)
  	   redirect_to admins_genres_path, notice: "ジャンルが更新されました"
    else
      render :edit
    end
  end

  private
  def genre_params
  	params.require(:genre).permit(:name, :is_valid)
  end

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
	before_action :authenticate_admins_user!
	def top
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters,if: :devise_controller?


	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana_name, :last_kana_name, :email, :postcode, :address, :phone_number])
	end

	def after_sign_in_path_for(resource_or_scope)
		if resource_or_scope.class == User
			'/admins/'
		elsif resource_or_scope.class == EndUser
			root_path
		else
		end
	end

	def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope == :admins_user
			new_admins_user_session_path
		elsif resource_or_scope == :end_user
			root_path
		else
		end
	end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  def search
  	#ジャンルに紐づく商品の探し方。whereメソッドでアイテムテーブルの中にあるジャンルＩＤを取り出す。
  	@items = Item.where(genre_id: params[:id])

  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/end_users_helper.rb
module Customers::EndUsersHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-4 col-xs-offset-1">
			<div class="title">
				<h2>ジャンル編集画面</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<%= form_for [:admins, @genre] do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>

			<div class="field">
				<%= f.label :ジャンル %>
				<%= f.text_field :name %>

				<%= f.label :is_valid, "販売中" %>
				<%= f.radio_button :is_valid, "販売中", class: "edit-control" %>
				<%= f.label :is_valid, "売切れ" %>
				<%= f.radio_button :is_valid, "売切れ", class: "edit-control" %>

				<%= f.submit "変更を保存する" , class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>
	<% end %>

app/views/admins/genres/index.html.erb
<% if flash[:notice] %>
<div class="flash">
	<%= flash[:notice] %>
</div>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<div class="title">
				<h2>ジャンル追加・一覧画面</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<%= form_for [:admins, @genre] do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>
			<div class="field">
				<%= f.label :ジャンル %>
				<%= f.text_field :name %>
				<%= f.label :is_valid, "販売中" %>
				<%= f.radio_button :is_valid, "販売中" %>
				<%= f.label :is_valid, "売切れ" %>
				<%= f.radio_button :is_valid, "売切れ" %>
				<%= f.submit "追加", class: "btn btn-primary" %>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<table class="table">
				<thead>
					<tr class="active">
						<th>ジャンル</th>
						<th>状態</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @genres.each do |genre| %>
					<tr>
						<td><%= genre.name %></td>
						<td><%= genre.is_valid %></td>
						<td><%= link_to "編集する", edit_admins_genre_path(genre), class: "btn btn-primary" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>