config/routes.rb
Rails.application.routes.draw do


  namespace :admins do
    root to: 'homes#top'
    devise_for :users, controllers: {
      sessions: 'admins/users/sessions',
      registrations: 'admins/users/registrations',
      passwords: 'admins/users/passwords'
    }
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  scope module: :customers do
    root to: 'homes#top'
    devise_for :end_users, controllers: {
      sessions: 'customers/end_users/sessions',
      registrations: 'customers/end_users/registrations',
      passwords: 'customers/end_users/passwords'
    }
    resources :end_users
    get 'end_users/:id/confirm' => 'end_users#confirm', as: :end_user_confirm
    patch 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: :withdrawal
    resources :items, only: [:index, :show]
    delete 'cart_items/empty' => 'cart_items#empty', as: :empty
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/thanks' => 'orders#thanks', as: :thanks
    post 'orders/confirm' => 'orders#confirm', as: :order_confirm
    resources :orders, only: [:index, :new, :create, :show]
    get 'homes/about' => 'homes#about', as: :about
    get 'genres/:id' => 'genres#search', as: :search
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :end_user
	belongs_to :item

	validates :quantity, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :end_user

	validates :direction, presence: true
	validates :address, presence: true
	validates :postcode, presence: true

	def full_address
		self.postcode + self.address + self.direction
	end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_kana_name, presence: true, format: { with: /\A[ぁ-んァ-ヶー－]+\z/ } #全角カタカナ
  validates :last_kana_name, presence: true, format: { with: /\A[ぁ-んァ-ヶー－]+\z/ }
  validates :postcode, presence: true, format: { with: /\A[0-9]+\z/ } #半角数字
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A[0-9]+\z/ }

  def active_for_authentication?
    super && (self.is_deleted == "有効")
  end

  enum is_deleted: {
    退会済: true,
    有効: false
  }

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy

	validates :name, presence: true

	enum is_valid: {
		売切れ: true,
		販売中: false
	}
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :image
	has_many :order_details, dependent: :destroy
	has_many :cart_items, dependent: :destroy
	belongs_to :genre

	validates :name, presence: true
	validates :detail, presence: true
	validates :non_taxed_price, presence: true
	validates :image, presence: true

	enum is_valid: {
		無効: true,
		有効: false
	}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user
	has_many :order_details, dependent: :destroy

	validates :direction, presence: true
	validates :address, presence: true
	validates :postcode, presence: true

	enum payment_type: {
		クレジットカード: 0,
		銀行振り込み: 1
	}

	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item

	enum item_status: {
		着手不可: 0,
		製作待ち: 1,
		製作中: 2,
		製作完了:3
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
	before_action :authenticate_admins_user!
	def top
	end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admins_user!
  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
    if @item.save
  	   	redirect_to admins_item_path(@item), notice: "商品が登録されました"
    else
      render :new
    end
  end

  def show
  	@item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item), notice: "商品情報が更新されました"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :detail, :genre_id, :non_taxed_price, :is_valid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters,if: :devise_controller?


	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana_name, :last_kana_name, :email, :postcode, :address, :phone_number])
	end

	def after_sign_in_path_for(resource_or_scope)
		if resource_or_scope.class == User
			'/admins/'
		elsif resource_or_scope.class == EndUser
			root_path
		else
		end
	end

	def after_sign_out_path_for(resource_or_scope)
		if resource_or_scope == :admins_user
			new_admins_user_session_path
		elsif resource_or_scope == :end_user
			root_path
		else
		end
	end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

	def index
		@items = Item.all
		# @item = Item.find(params[:id])
		@items = Item.page(params[:page])
	end

	def show
		@item = Item.find(params[:id])
		@cart_item = CartItem.new
	end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/end_users_helper.rb
module Customers::EndUsersHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<div class="title">
				<h2>商品編集画面</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-3 col-xs-offset-1">
			<%= form_for [:admins, @item] do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>

			<div class="field">
				<%= attachment_image_tag(@item, :image, size: "200x200", fallback: "no_image.png") %>
				<%= f.attachment_field :image %>
			</div>
		</div>
		<div class="col-xs-5">
			<div class="row">
				<div class="col-xs-4 ">
					<%= f.label :商品名 %>
				</div>
				<div class="col-xs-6">
					<%= f.text_field :name %>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-4 ">
					<%= f.label :商品説明 %>
				</div>
				<div class="col-xs-4">
					<%= f.text_area :detail %>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-4 ">
					<%= f.label :ジャンル %>
				</div>
				<div class="col-xs-6">
					<%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
				</div>
			</div>


			<div class="row">
				<div class="col-xs-4 ">
					<%= f.label :税抜価格 %>
				</div>
				<div class="col-xs-7">
					<%= f.text_field :non_taxed_price %> 円
				</div>
			</div>

			<div class="row">
				<div class="col-xs-4 ">
					<%= f.label :販売ステータス %>
				</div>
				<div class="col-xs-6">
					<%= f.select :is_valid, [["販売中","有効"],["売切れ","無効"]] %>
				</div>
			</div>

		</div>
	</div>
	<div class="row">
		<div class="col-xs-3 col-xs-offset-7">
			<%= f.submit "変更を保存", class: "btn btn-primary"  %>
		</div>
		<% end %>
	</div>
</div>

app/views/admins/items/index.html.erb
<% if flash[:notice] %>
<div class="flash">
	<%= flash[:notice] %>
</div>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-xs-3 col-xs-offset-1">
			<h2>商品一覧画面</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<table class="table">
				<thead>
					<tr class="active">
						<th>商品ID</th>
						<th>商品名</th>
						<th>税込価格</th>
						<th>ジャンル</th>
						<th>ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @items.each do |item| %>
					<tr>
						<td><%= item.id %></td>
						<td>
							<%= link_to admins_item_path(item) do %>
							<%= item.name %>
							<% end %>
						</td>
						<td><%= item.non_taxed_price.floor.to_s(:delimited) %></td>
						<td><%= item.genre.name %></td>
						<td><%= item.is_valid %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<div class="row">
				<div class="col-xs-3 col-xs-offset-1">
					<%= link_to "商品新規登録", new_admins_item_path, class: "btn btn-primary" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-5">
			<div class="title">
				<h2>商品新規登録画面</h2>
			</div>
		</div>
	</div>
	<%= form_for [:admins, @item] do |f| %>
	<%= render 'layouts/error_messages', model: f.object %>
	<div class="row">
		<div class="col-xs-1 col-xs-offset-1">
			<%= attachment_image_tag(@item, :image, size: "200x200", fallback: "no_image.png") %>
		</div>
		<div class="col-xs-4 col-xs-offset-2 ">
			<%= f.label :商品名 %>
			<%= f.text_field :name %>
		</div>
		<div class="col-xs-4  col-xs-offset-2  ">
			<%= f.label :商品説明 %>
			<%= f.text_area :detail %>
		</div>
		<div class="col-xs-4  col-xs-offset-2  ">
			<%= f.label :ジャンル %>
			<%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
		</div>
		<div class="col-xs-4  col-xs-offset-2 ">
			<%= f.label :税抜価格 %>
			<%= f.text_field :non_taxed_price %> 円
		</div>
		<div class="col-xs-4  col-xs-offset-2  ">
			<%= f.label :販売ステータス %>
			<%= f.select :is_valid, [["販売中","有効"],["売切れ","無効"]] %>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-1 col-xs-offset-2 ">
			<%= f.attachment_field :image %>
		</div>
		<div class="col-xs-1 col-xs-offset-3 ">
			<%= f.submit "新規登録",class: "btn btn-primary" %>
		</div>
	</div>
	<% end %>
</div>

app/views/admins/items/show.html.erb
<% if flash[:notice] %>
<div class="flash">
	<%= flash[:notice] %>
</div>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<div class="title">
				<h2>商品詳細画面</h2>
			</div>

		</div>
	</div>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<%= attachment_image_tag(@item, :image, size: "200x200", fallback: "home-baked-cake.jpg") %>
		</div>
		<div class="col-xs-8 col-xs-offset-1">
			<div class="row">
				<div class="col-xs-2 ">
					<div>商品名</div>
				</div>
				<div class="col-xs-6">
					<%= @item.name %>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-2 ">
					<div>商品説明</div>
				</div>
				<div class="col-xs-6">
					<%= @item.detail %>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-2 ">
					<div>ジャンル</div>
				</div>
				<div class="col-xs-6">
					<%= @item.genre.name %>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-3 ">
					<div>税込価格(税抜価格)</div>
				</div>
				<div class="col-xs-6">
					¥<%= ((@item.non_taxed_price)*1.1).floor.to_s(:delimited) %>(¥<%= @item.non_taxed_price.floor.to_s(:delimited) %>)
				</div>
			</div>
			<div class="row">
				<div class="col-xs-3 ">
					<h5>販売ステータス</h5>
				</div>
				<div class="col-xs-6">
					<%= @item.is_valid %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-3 col-xs-offset-7">
			<%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-primary" %>
		</div>
	</div>
</div>